// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeEjzrAzC2dSQ2S8qn1hIHR1zVbJebz0',
    appId: '1:432008081086:web:9952247f5b939f837e38ef',
    messagingSenderId: '432008081086',
    projectId: 'york-game-shield',
    authDomain: 'york-game-shield.firebaseapp.com',
    databaseURL: 'https://york-game-shield-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'york-game-shield.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7tFtWItACVGY1QcmfF9TDrhboj7QqvA',
    appId: '1:432008081086:android:a79639540deaa46e7e38ef',
    messagingSenderId: '432008081086',
    projectId: 'york-game-shield',
    databaseURL: 'https://york-game-shield-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'york-game-shield.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-it0ZZQ1NTPnQWb_rd83WkolrnKyUP2k',
    appId: '1:432008081086:ios:4d3607bbf33d0db07e38ef',
    messagingSenderId: '432008081086',
    projectId: 'york-game-shield',
    databaseURL: 'https://york-game-shield-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'york-game-shield.appspot.com',
    iosBundleId: 'com.example.testApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-it0ZZQ1NTPnQWb_rd83WkolrnKyUP2k',
    appId: '1:432008081086:ios:001db15060a2425a7e38ef',
    messagingSenderId: '432008081086',
    projectId: 'york-game-shield',
    databaseURL: 'https://york-game-shield-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'york-game-shield.appspot.com',
    iosBundleId: 'com.example.testApplication.RunnerTests',
  );
}
